### ISSUE TITLE
"No good"/Undo does not undo first-offs

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#16]
https://user-images.githubusercontent.com/47470230/128951787-ba575fa7-c22e-41a5-a745-1d87a1d0bb69.MOV

**Comment by mattandwhatnot** [comment]
this is working as designed. (although the design is not irrefutable)

An item can be a no good first off but still continue to the next process. In most cases that failed item will continue to an inspection step where it flaws are entered and repair/reinspection occurs. The item is not rebuilt, so the first-off is not repeated on that particular item.

Although, canceling that first-off does trigger one of the other items in the work order pass as the required minimum one good first-off.

Does this still map correctly to real-world process?
At the very least this highlights a need in the Help Docs

**Comment by AlexLT1** [comment]
As far as I know the undo button is not very often used, unless something
goes wrong and someone missed the button in the production view. Since you
increased the duration I haven't heard that happen.

While I was resting this out I only had one item in the order  so there was
no other item for the required minimum of one first off. I'll keep that in
mind when I go to look at other things to add several items.

**Comment by mattandwhatnot** [comment]
If a first-off is cancelled because it does not meet requirements then another separate item should be produced for a "first" verification.
If the order quantity is small enough, it is plausible that all items might fail to meet requirements and the order does not have a good first-off. This does not cause any downline problems.
If the entry is cancelled because of an error, it is still possible to re-record the same first-off on the same item through the Repeat Step function.

This is determined to be a non-issue. Software path follows process.
