### ISSUE TITLE
Seaarchable bugs (NON-URGENT)

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#54]
Here is a short video showing what I had found. The one I'm unsure of is the last one. As mentioned, I did find others not that didn't match what was written in the name, but after a long list of attempts, I thought to bring it to your attention. 

https://user-images.githubusercontent.com/47470230/202540720-3738f64b-943c-4866-9e97-8815df9e590d.mp4

**Comment by mattandwhatnot** [comment]
Someone mistakenly setup the customer Gradient to point to the editing page instead of the public page
Docs/Pisces was a property/case-sensitive issue.

Exact One's short name in neptune is EXACT1. 
I think this highlights a need for fuzzy customer search here. So I have added partial search for customer names. If an exact match can't be found it will look for your query as part of the full name or the abbreviation. If only one partial result is found, the view will redirect automatically.

Changes in version 3.13.1+
